# worker_processes 1;

# events { worker_connections 1024; }

# http {
#     lua_shared_dict my_cache 10m;

#     resolver 127.0.0.11 ipv6=off;

#     server {
#         listen 80;

#         location / {
#             content_by_lua_file /etc/nginx/lua/cache.lua;
#         }
#     }
# }

# worker_processes 1;

# events { worker_connections 1024; }

# http {
#     lua_shared_dict my_cache 10m;

#     resolver 127.0.0.11 ipv6=off;

#     server {
#         listen 80;

#         # Serve frontend
#         location / {
#             root /usr/local/openresty/nginx/html;
#             index index.html;
#         }

#         # Endpoint para registrar visita
#         location /visit {
#             content_by_lua_file /etc/nginx/lua/counter.lua;
#         }

#         # Endpoint SSE
#         location /events {
#             content_by_lua_file /etc/nginx/lua/sse.lua;
#         }
#     }
# }


worker_processes 1;

events { worker_connections 1024; }

http {
    lua_shared_dict my_cache 10m;

    resolver 127.0.0.11 ipv6=off;

    server {
        listen 80;

        location / {
            root /usr/local/openresty/nginx/html;
            index index.html;
        }

        location /visit {
            content_by_lua_file /etc/nginx/lua/counter.lua;
        }

        location /events {
            content_by_lua_file /etc/nginx/lua/sse_manager.lua;
            proxy_buffering off;
        }
    }
}
